"""Fantasy League HQ provider-normalization, identity, sync, and change-detection foundation."""

from .changes import (
    FantasyChangeEvent,
    FantasySnapshot,
    UnsafeSnapshotTransition,
    derive_fantasy_change_events,
)
from .identity import (
    MATCHED,
    NEEDS_REVIEW,
    PRE_GSIS,
    TEAM_DEFENSE,
    UNRESOLVED,
    SleeperIdentityResolution,
    extract_propwar_player_ids,
    load_ffverse_player_ids,
    resolve_sleeper_player,
    resolve_sleeper_players,
    validate_ffverse_player_ids,
)
from .models import (
    DraftPick,
    DraftState,
    FaabTransfer,
    FantasyLeagueState,
    LeagueRules,
    LeagueTransaction,
    Manager,
    MatchupTeam,
    Roster,
    TradedPick,
    WeeklyLeagueState,
)
from .sleeper import (
    SleeperClient,
    SleeperLeagueBundle,
    normalize_sleeper_bundle,
    normalize_sleeper_draft_picks,
    normalize_sleeper_matchups,
    normalize_sleeper_transactions,
)
from .sync import (
    FantasyIdentityAudit,
    SleeperSyncResult,
    build_sleeper_identity_audit,
    build_sleeper_sync_result,
    collect_league_player_ids,
)

__all__ = [
    "DraftPick",
    "DraftState",
    "FaabTransfer",
    "FantasyChangeEvent",
    "FantasyIdentityAudit",
    "FantasyLeagueState",
    "FantasySnapshot",
    "LeagueRules",
    "LeagueTransaction",
    "MATCHED",
    "Manager",
    "MatchupTeam",
    "NEEDS_REVIEW",
    "PRE_GSIS",
    "Roster",
    "SleeperClient",
    "SleeperIdentityResolution",
    "SleeperLeagueBundle",
    "SleeperSyncResult",
    "TEAM_DEFENSE",
    "TradedPick",
    "UNRESOLVED",
    "UnsafeSnapshotTransition",
    "WeeklyLeagueState",
    "build_sleeper_identity_audit",
    "build_sleeper_sync_result",
    "collect_league_player_ids",
    "derive_fantasy_change_events",
    "extract_propwar_player_ids",
    "load_ffverse_player_ids",
    "normalize_sleeper_bundle",
    "normalize_sleeper_draft_picks",
    "normalize_sleeper_matchups",
    "normalize_sleeper_transactions",
    "resolve_sleeper_player",
    "resolve_sleeper_players",
    "validate_ffverse_player_ids",
]
