from datetime import datetime,timezone
import pandas as pd
from src.common import output_path,project_path
from src.load.build_current_role_map import build_map_from_frames,discover_real_inputs
def add(rows,name,expected,actual,passed):rows.append({"check_name":name,"expected":str(expected),"actual":str(actual),"status":"PASS" if passed else "FAIL","severity":"INFO" if passed else "HIGH","notes":""})
def fixture_identity():return pd.DataFrame([("TEST-001","Fixture Quarterback","fixture quarterback","IND","QB"),("TEST-002","Fixture Receiver","fixture receiver","MIA","WR"),("TEST-003","Fixture Runner","fixture runner","PHI","RB"),("TEST-004","Fixture Tight End","fixture tight end","KC","TE")],columns=["player_id","player_name","normalized_player_name","team","position"]).assign(season_max=2025)
def fixture_roster():return pd.DataFrame([("TEST-001","IND","READY"),("TEST-002","MIA","READY"),("TEST-003","PHI","READY"),("TEST-004","KC","READY")],columns=["player_id","current_team","team_mapping_status"])
def validate_current_role_map():
 rows=[];mp=output_path("roles/current_role_map.csv");sp=output_path("roles/current_role_map_status.csv");rp=output_path("roles/current_role_needs_review.csv")
 for n,p in [("current_role_map_exists",mp),("current_role_status_exists",sp),("current_role_review_exists",rp)]:add(rows,n,True,p.exists(),p.exists())
 status=pd.read_csv(sp,low_memory=False) if sp.exists() else pd.DataFrame();production="MISSING" if status.empty else str(status.status.iloc[0]);real,over=discover_real_inputs(project_path("data","gates","roles"));add(rows,"templates_do_not_count_as_real_data","templates ignored",f"real_files={len(real)}; status={production}",bool(real) or production=="NEEDS DATA");add(rows,"missing_role_data_stays_needs_data","NEEDS DATA when no real files",production,bool(real) or production=="NEEDS DATA")
 f=project_path("tests","fixtures");roles=pd.read_csv(f/"current_role_sample.csv",low_memory=False);ovs=pd.read_csv(f/"role_overrides_sample.csv",low_memory=False);mapped=build_map_from_frames(roles,ovs,fixture_identity(),fixture_roster());by=mapped.set_index("player_id",drop=False)
 add(rows,"clear_starter_ready","READY",by.loc["TEST-001","role_mapping_status"],by.loc["TEST-001","role_mapping_status"]=="READY");add(rows,"unknown_low_role_review","NEEDS REVIEW",by.loc["TEST-002","role_mapping_status"],by.loc["TEST-002","role_mapping_status"]=="NEEDS REVIEW");add(rows,"approved_override_ready","READY",by.loc["TEST-003","role_mapping_status"],by.loc["TEST-003","role_mapping_status"]=="READY" and bool(by.loc["TEST-003","manual_override"]));missing=mapped[mapped.player_name.eq("Fixture Tight End")].iloc[0];add(rows,"missing_id_review","NEEDS REVIEW",missing.role_mapping_status,missing.role_mapping_status=="NEEDS REVIEW");add(rows,"unmatched_player_blocked","BLOCKED",by.loc["TEST-999","role_mapping_status"],by.loc["TEST-999","role_mapping_status"]=="BLOCKED");unsafe=mapped[mapped.role_confidence.astype(str).str.lower().isin({"low","unknown",""})&mapped.role_mapping_status.eq("READY")&~mapped.manual_override.map(bool)];add(rows,"low_unknown_roles_cannot_silently_pass",0,len(unsafe),unsafe.empty)
 ready=output_path("google_sheets/live_readiness_export.csv");d=pd.read_csv(ready,low_memory=False) if ready.exists() else pd.DataFrame();x=d.loc[d.get("Gate",pd.Series(dtype=str)).eq("Final Betting Use"),"Status"] if not d.empty else pd.Series(dtype=str);final=str(x.iloc[0]) if not x.empty else "MISSING";add(rows,"role_validation_does_not_enable_live","NO-GO",final,final=="NO-GO");report=pd.DataFrame(rows);overall="PASS" if report.status.eq("PASS").all() else "FAIL";report.to_csv(output_path("run_reports/latest_current_role_map_validation.csv"),index=False);failed=report[report.status.eq("FAIL")].check_name.tolist();output_path("run_reports/latest_current_role_map_validation.md").write_text(f"# Current Role Map Validation\n\nRun timestamp: `{datetime.now(timezone.utc).isoformat()}`\n\nOverall status: `{overall}`\n\nProduction role-map status: `{production}`\n\nReal role files: `{len(real)}`\n\nOverride files: `{len(over)}`\n\nTemplates counted as data: `False`\n\nFixture validation: `SYNTHETIC TEST ONLY`\n\nFailed checks: `{', '.join(failed) if failed else 'None'}`\n\nFinal live readiness: `{final}`\n\nNext required action: Load source-backed non-template role data and resolve every review/blocking row before forward use.\n",encoding="utf-8");return report,overall
def main():
 r,o=validate_current_role_map();print(f"Current role map validation: {o}");print(f"Failed checks: {int(r.status.eq('FAIL').sum())}")
if __name__=="__main__":main()
