from datetime import datetime,timezone
import pandas as pd
from src.common import output_path,project_path
from src.load.build_current_injury_map import build_map_from_frames,discover_real_inputs
def add(rows,n,e,a,p):rows.append({"check_name":n,"expected":str(e),"actual":str(a),"status":"PASS" if p else "FAIL","severity":"INFO" if p else "HIGH","notes":""})
def identities():return pd.DataFrame([("TEST-001","Fixture Quarterback","fixture quarterback"),("TEST-002","Fixture Receiver","fixture receiver"),("TEST-003","Fixture Runner","fixture runner"),("TEST-004","Fixture Tight End","fixture tight end"),("TEST-005","Fixture Safety Valve","fixture safety valve")],columns=["player_id","player_name","normalized_player_name"])
def roster():return pd.DataFrame([("TEST-001","IND","READY"),("TEST-002","MIA","READY"),("TEST-003","PHI","READY"),("TEST-004","KC","READY"),("TEST-005","BUF","READY")],columns=["player_id","current_team","team_mapping_status"])
def roles():return pd.DataFrame([("TEST-001","Starting quarterback"),("TEST-002","Starting receiver"),("TEST-003","Lead back"),("TEST-004","Starting tight end")],columns=["player_id","projected_role"])
def validate_current_injury_map():
 rows=[];mp=output_path("injuries/current_injury_map.csv");sp=output_path("injuries/current_injury_map_status.csv");rp=output_path("injuries/current_injury_needs_review.csv")
 for n,p in [("current_injury_map_exists",mp),("current_injury_status_exists",sp),("current_injury_review_exists",rp)]:add(rows,n,True,p.exists(),p.exists())
 status=pd.read_csv(sp,low_memory=False) if sp.exists() else pd.DataFrame();production="MISSING" if status.empty else str(status.status.iloc[0]);real,over=discover_real_inputs(project_path("data","gates","injuries"));add(rows,"templates_do_not_count_as_real_data","templates ignored",f"real_files={len(real)}; status={production}",bool(real) or production=="NEEDS DATA");add(rows,"missing_injury_data_stays_needs_data","NEEDS DATA when no real files",production,bool(real) or production=="NEEDS DATA")
 f=project_path("tests","fixtures");inj=pd.read_csv(f/"current_injury_sample.csv",low_memory=False);ov=pd.read_csv(f/"injury_overrides_sample.csv",low_memory=False);m=build_map_from_frames(inj,ov,identities(),roster(),roles());by=m.set_index("player_id",drop=False);add(rows,"healthy_full_active_ready","READY",by.loc["TEST-001","injury_mapping_status"],by.loc["TEST-001","injury_mapping_status"]=="READY");add(rows,"questionable_limited_review","NEEDS REVIEW",by.loc["TEST-002","injury_mapping_status"],by.loc["TEST-002","injury_mapping_status"]=="NEEDS REVIEW");add(rows,"out_blocked","BLOCKED",by.loc["TEST-003","injury_mapping_status"],by.loc["TEST-003","injury_mapping_status"]=="BLOCKED");add(rows,"approved_override_applied","READY",by.loc["TEST-004","injury_mapping_status"],by.loc["TEST-004","injury_mapping_status"]=="READY" and bool(by.loc["TEST-004","manual_override"]));missing=m[m.player_name.eq("Fixture Safety Valve")].iloc[0];add(rows,"missing_id_review","NEEDS REVIEW",missing.injury_mapping_status,missing.injury_mapping_status=="NEEDS REVIEW");add(rows,"unmatched_player_blocked","BLOCKED",by.loc["TEST-999","injury_mapping_status"],by.loc["TEST-999","injury_mapping_status"]=="BLOCKED");unsafe_block=m[(m.injury_status.astype(str).str.lower().isin({"out","ir","pup","suspended"})|m.game_status.astype(str).str.lower().isin({"out","inactive"}))&m.injury_mapping_status.eq("READY")&~m.manual_override.map(bool)];add(rows,"unavailable_statuses_cannot_pass",0,len(unsafe_block),unsafe_block.empty);unsafe_review=m[(m.injury_status.astype(str).str.lower().isin({"questionable","unknown"})|m.practice_status.astype(str).str.lower().isin({"limited","unknown"}))&m.injury_mapping_status.eq("READY")&~m.manual_override.map(bool)];add(rows,"questionable_unknown_cannot_pass",0,len(unsafe_review),unsafe_review.empty)
 ready=output_path("google_sheets/live_readiness_export.csv");d=pd.read_csv(ready,low_memory=False) if ready.exists() else pd.DataFrame();x=d.loc[d.get("Gate",pd.Series(dtype=str)).eq("Final Betting Use"),"Status"] if not d.empty else pd.Series(dtype=str);final=str(x.iloc[0]) if not x.empty else "MISSING";add(rows,"injury_validation_does_not_enable_live","NO-GO",final,final=="NO-GO");report=pd.DataFrame(rows);overall="PASS" if report.status.eq("PASS").all() else "FAIL";report.to_csv(output_path("run_reports/latest_current_injury_map_validation.csv"),index=False);failed=report[report.status.eq("FAIL")].check_name.tolist();output_path("run_reports/latest_current_injury_map_validation.md").write_text(f"# Current Injury Map Validation\n\nRun timestamp: `{datetime.now(timezone.utc).isoformat()}`\n\nOverall status: `{overall}`\n\nProduction injury-map status: `{production}`\n\nReal injury files: `{len(real)}`\n\nOverride files: `{len(over)}`\n\nTemplates counted as data: `False`\n\nFixture validation: `SYNTHETIC TEST ONLY`\n\nFailed checks: `{', '.join(failed) if failed else 'None'}`\n\nFinal live readiness: `{final}`\n\nNext required action: Load source-backed non-template injury data and resolve every review/blocking row before forward use.\n",encoding="utf-8");return report,overall
def main():
 r,o=validate_current_injury_map();print(f"Current injury map validation: {o}");print(f"Failed checks: {int(r.status.eq('FAIL').sum())}")
if __name__=="__main__":main()
